resolver: lts-20.16

flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
  - "."
extra-deps:
  - skylighting-core-0.13
  - skylighting-0.13
  - skylighting-format-ansi-0.1
  - skylighting-format-latex-0.1
  - skylighting-format-blaze-html-0.1
  - emojis-0.1.2
  - gridtables-0.0.3.0
  - lpeg-1.0.3
  - aeson-pretty-0.8.9
  - unicode-transforms-0.4.0.1
  - unicode-data-0.3.0
  - commonmark-pandoc-0.2.1.2
  - ipynb-0.2
  - pandoc-types-1.22.2.1
  - commonmark-0.2.2
  - commonmark-extensions-0.2.3.2
  - doclayout-0.4
  - doctemplates-0.10.0.2
  - citeproc-0.8.0.1
  - texmath-0.12.5.2

  - git: https://github.com/baulig/hslua.git
    commit: 65e37da6081773bdb324dafc1a2285cf1b497382
    subdirs:
      - hslua
      - hslua-aeson
      - hslua-classes
      - hslua-core
      - hslua-marshalling
      - hslua-module-path
      - hslua-module-system
      - hslua-module-text
      - hslua-module-version
      - hslua-objectorientation
      - hslua-packaging
      - lua
      - lua-arbitrary
      - tasty-hslua
      - tasty-lua

  - hslua-module-doclayout-1.0.4
  - pandoc-lua-marshal-0.1.7

ghc-options:
  "$locals": -fhide-source-paths -Wno-missing-home-modules
nix:
  packages: [zlib]
